### ISSUE TITLE
messages are sometimes lost

### ISSUE THREAD

**Issue by sena73** [guardianproject/ChatSecureAndroid#196]
I use Gibberbot to chat using Google-talk account. Other side is mostly Pidgin on Debian GNU/Linux. Sometimes messages that are sent from Pidgin to Gibberbot are simply lost. There is no error message or something on any side of communication. That is really bad since most of the time I do not notice that message is lost. I never have such a problem with Pidgin<->Pidgin. I believe this is very serious bug.

Please ask questions if you need more info. I will temporary switch to Xabber now.

**Comment by tejasinamdar** [comment]
We have developed the plugin to ensure that no messages are lost (in the context of Openfire).
Using Openfire, in the presence of a weak network, messages/packets are lost.
Hence, to ensure deliveries (at-least-once) and no message/packet losses we have developed the plugin.
The plugin ensures 'Stanza Acknowledgements' (the ability to know if messages have been received by one's peers) with no losses (at-least-once deliveries).

For more information, please see-
https://www.atklique.com/bridge/blog/?q=node/5

For more information (and integration of the plugin with Openfire), please drop an email to support@atklique.com with you requirements.
