### ISSUE TITLE
Heartbeat setting does not have any effect

### ISSUE THREAD

**Issue by lesac** [guardianproject/ChatSecureAndroid#242]
I'm using v11 RC5 on Cyanogenmod 10.1.2. Setting heartbeat interval does not change Gibberbot's behaviour. In fact, a wakelock detector shows that Gibberbot calls IM_HEARTBEAT every minute. This does affect battery consumption seriously.

How, regarding this issue, does Gibberbot actually differ from gtalk? On my phone I do not have a battery issue with gtalk running.

Many thanks

**Comment by unhammer** [comment]
Could https://github.com/chatsecure/chatsecure-push-server also be used for chatsecure-android? 

I noticed ChatSecure used 30MB of my data plan in under 5 days, where I had at most a ten-line chat while not on wifi, so it's not just battery being affected :-)

**Comment by chrisballinger** [comment]
XMPP is a very noisy / verbose protocol that was clearly designed in the
desktop era. The extra data use you are seeing is most likely related to
unneeded roster updates in the background and things like avatar image
downloads.

**Comment by unhammer** [comment]
Ouch. Couldn't that be done only when it's in the foreground?

**Comment by n8fr8** [comment]
We are definitely thinking about how to stop the server from sending roster data you aren't interested in. I think the new v14.1 beta release has some improvements on this front. We should also probably allow you to turn off avatar loading entirely.

@unhammer how many people are on your contact/buddy/roster list (roughly)?

**Comment by unhammer** [comment]
~30
