### ISSUE TITLE
ChatSecure 12.4.2 incompatibilities with bitlbee

### ISSUE THREAD

**Issue by micahflee** [guardianproject/ChatSecureAndroid#281]
I decided to try the newest version of ChatSecure from https://guardianproject.info/releases/ChatSecure-v12.4.2-release.apk. I happened to be trying it with someone else (also, confusingly, named Micah) using bitlbee. Whenever I try creating a new OTR session it still says that encryption is off but it displays "error decrypting" OTR errors. It doesn't seem to work to start an OTR session with him.

My guess is this is an implementation bug in either ChatSecure or in bitlbee.

![screenshot_2013-09-25-16-08-54](https://f.cloud.github.com/assets/156128/1212811/aab9e320-261e-11e3-834b-823b0b1f1614.png)

**Comment by n8fr8** [comment]
this was fixed long ago i am happy to say!
