### ISSUE TITLE
Disable back botton with one account

### ISSUE THREAD

**Issue by eloydegen** [guardianproject/ChatSecureAndroid#320]
I think that the screen with the conversation list should be the 'main' screen. Especially when you have only one chat account, the back button at the left upper corner is not really useful because the position of the button suggest that it is NOT the 'main' screen.

My suggestion is to disable the back button on the conversation screen (the Android back button go back to the prev. screen) when you have only one account, because you can always add one via the settings menu.

**Comment by unhammer** [comment]
was this fixed? when I click ← from the conversation screen, I get to the android home screen
