### ISSUE TITLE
Sharing shows no effect

### ISSUE THREAD

**Issue by p23fr** [guardianproject/ChatSecureAndroid#417]
If I want to share from another app (for example play store) to a contact this does not show any effect. I choose Chatsecure from "share" to options, then I get to the point where I can choose account, then to contacts overview where I choose one but it will only open the conversation and no sharing takes place at all (OTR is active for this conversation).

**Comment by n8fr8** [comment]
I think we've fixed this, or at least it works for content/apps that we support sharing.
