### ISSUE TITLE
Message never arrive if server lost or network change to wifi or 3g

### ISSUE THREAD

**Issue by nitmee** [guardianproject/ChatSecureAndroid#428]
The problem cames when a device change the network ( change from 3g to WiFi, change 3g IP. or the device lost the network ( turn off 3g, wifi or lost connection ). The server thinks that the device is online and send the message but it (obviusly) never arrive try to fix this or any other option like automatic resend if network or user is online/available .

**Comment by n8fr8** [comment]
We have implemented improved auto-resend, and now also show delivery confirmation check marks.
