### ISSUE TITLE
No secure communcation (always red)

### ISSUE THREAD

**Issue by GitterHubby** [guardianproject/ChatSecureAndroid#432]
I set up ChatSecure on two Android 2.3 Smartphones (HTC Wildfire S).  Several Icons in the top bar are invisible (I find them by accident). The communcation works and on 1 Smartphone, the communication was green (= secured) for a while. But after that short time, no matter what I did (reinstalled, misc configuration changes), everything is red always, i.e. no secure chatting possible.

**Comment by n8fr8** [comment]
This is now fixed.
