### ISSUE TITLE
File transfer: "Accept file" message in chat/conversation

### ISSUE THREAD

**Issue by CarlVanHouten** [guardianproject/ChatSecureAndroid#452]
I've tested ChatSecure intensively 2 days and I realized that every time I want to transfer a file, nobody of my contacts realized the information (window) that there is a file transfer waiting.

It happened to me, too. One click too much and it's gone. And because it is not ringing when a file comes in, nobody takes a look. ( I have to tell "Hey, i'll send you a file, is that okay?" )

IMHO I'd prefer following...

- File transfer notification in the chat window ( "*ring-ring* Oh, a message! Oh, a file. -> accept)
- This "accept always" should be (optionally) -really- always, not only in one session.
- Optional: Choose to recive file formats (images) automatically : jpg, gif, png
(you want to send somebody a funny picture, then it should just appear)
-or-
- Optional: Choose to recive files up to 20kb, 50kb, 100kb automatically

Best regards

**Comment by n8fr8** [comment]
This is being added for v15... it is partially in v14 where you just need to accept once, and also we have a notification now.
