### ISSUE TITLE
translations for the website and documentaiton

### ISSUE THREAD

**Issue by hermann-san** [guardianproject/ChatSecureAndroid#460]
is there any plan to translate the website into different languages?
How about documentation?  FAQ, Tutorials, readme's , etc.  Is there anything that can be translated?
I am will to help translating.

**Comment by n8fr8** [comment]
Transifex is where we put everything, and now have our play store/app description up there. Please help make sure that is translated, as it is the text we will use there, and on our site:


https://www.transifex.com/projects/p/chatsecureandroid/viewstrings/#en/play-store
