### ISSUE TITLE
Automatic picture/image resize

### ISSUE THREAD

**Issue by CarlVanHouten** [guardianproject/ChatSecureAndroid#465]
It would be great, if images could be resized automatically to a choose resolution. Today's smartphones have high resolution cams, so a picture can be 5-9mb easily. 

640x480 would be pretty good and quickly transferred.   Or just as an option in the settings with some resolutions. Full resolution could be sent by "send file". 

Now I have to take the picture, open quickpic (image app) , menu, edit, choose resolution, save, back to ChatSecure, send picture.

**Comment by n8fr8** [comment]
This is now happening for pictures you take from within chatsecure, and in 14.2 will happen with imported photos as well.
