### ISSUE TITLE
[Feature Request] Onioncat Android Port

### ISSUE THREAD

**Issue by HulaHoopWhonix** [guardianproject/ChatSecureAndroid#495]
Hi. I'm a contributor for the Tor centric Whonix project [https://www.whonix.org]. We are almost at a point where we can get p2p VOIP working with Jitsi between two parties running under Tor on the desktop. This is done with the assistance of Onioncat becuase it allows IPv6 and UDP to be tunneled over Tor internally.

Onioncat creates an anonymous VPN between clients running a Tor Hidden Service. It really opens up the possibilities for many uses.
https://www.onioncat.org/

Please consider making an Onioncat port for Android to extend the ability of anonymous VOIP to phone users too. Linphone and Jitsi already have Android clients which can meet this important need.

Thanks.

**Comment by n8fr8** [comment]
Love this idea, but this is not the right place for the ticket!

**Comment by rahra** [comment]
Just a note for those interested in running OnionCat on Android:
1.) Checkout OnionCat from its svn repository. It contains a script to cross-compile for Android:
`svn checkout https://www.cypherpunk.at/svn/onioncat/trunk onioncat`
2.) Cd into the folder "onioncat"
3.) Probably you have to run `autoreconf` dependent on the version of autotools.
4.) Run `./android/android_configure` (you have to have installed the Android-NDK)
5.) Run `make`
6.) You'll find the ARM binary in "src/ocat". Copy it to your smartphone device and run it as root. (you have to have "Orbot" installed on your device)
