### ISSUE TITLE
Send files from Google Drive and Dropbox only?

### ISSUE THREAD

**Issue by venzen** [guardianproject/ChatSecureAndroid#504]
Thanks for this. One of the only XMPP clients that can transfer files.

When sending a file, the file selection dialogue offers me 2 choices: select from Google Drive or from Dropbox. 

Is it possible to select a file from the local filesystem? Users may want to send a recording they made or photo they took with the device.

**Comment by n8fr8** [comment]
I hope you are still using ChatSecure. We've improved the audio file playback support, and are working on a major update to media sharing in our v15 release coming this summer!
