### ISSUE TITLE
App Lock Password - NOT WORKING

### ISSUE THREAD

**Issue by unknerror** [guardianproject/ChatSecureAndroid#537]
Hello, I think I've found a bug, this is the scenario:

Right after the app install, when opening it for the very first time, it will ask you if you desire to password protect (lock) the application on opening.

Sadly, it dose NOT matter If I go with the option "Set a Password" or how many times I "tap/click",
as it will not gonna work. In the Google Play version, it is happening nothing, and in the other versions the "password screen menu" is getting Killed/Closed.

I have tried these versions:
1) From the Website Version 14.0.3 => https://guardianproject.info/releases/chatsecure-latest.apk
2) From Google Play Store 14.0.4 => https://play.google.com/store/apps/details?id=info.guardianproject.otr.app.im&hl=en
3) From F-Droid 13.1.2 AND  the old deprecated one "Gibberbot" 0.0.11-RC5
https://f-droid.org/repository/browse/?fdfilter=chat&fdid=info.guardianproject.otr.app.im

 This is the Scenario:
1.  When starting the app, app Lock passwd input is NOT possible
2. The user is expecting at this step to be able to input a passwd / swipe / pin lock
3.  After staring the app there is no App Lock passwd menu available
4. At this step, the user is expecting to change the lock pin / passwd from whitin the app settings.

Here is the a video ==>> http://youtu.be/RzmZgKum5Og <<==

**Comment by orblivion** [comment]
I'm going to second @unknerror here actually. The "password" field was also not very clearly marked, to me. I came here also thinking this feature was broken. I can't say why for sure, but I would consider having somebody with UI experience look at it and figure out why.

**Comment by orblivion** [comment]
If it were up to me, I'd have a header font that says "Set Password" for the dialog. And then have the button say "Submit" or similar. I think this is more like what people are used to.
