### ISSUE TITLE
Status is broken

### ISSUE THREAD

**Issue by aruso** [guardianproject/ChatSecureAndroid#592]
Seems like sometime around 14.0.6 status broke. To recreate the issue log into 2 devices using 2 accounts and login. Then logout with both and log back in ... Status (green circle) never updates to show the contact is back online but the 2 parties can establish OTR and communicate.

**Comment by aruso** [comment]
FYI dont know if this was worked on but as of 14.1 beta 2 this is still better but still an  issue.

**Comment by n8fr8** [comment]
i believe this was fixed, and if not we are double checking for 14.2
