### ISSUE TITLE
verify fingerprint has no response.

### ISSUE THREAD

**Issue by WillMorrison** [guardianproject/ChatSecureAndroid#601]
My app (android chatsecure v14.0.9) has gotten into a state where tapping the verify fingerprint menu item does nothing, while the chat is encrypted but unverified. This is the case for both my google account and my duckduckgo XMPP account. This issue also looks similar to https://dev.guardianproject.info/issues/4182 for facebook accounts.

I have confirmed that the other people I'm talking with can verify my fingerprint.

**Comment by n8fr8** [comment]
fixed in 14.1.1
