### ISSUE TITLE
wrong name shown after chat closed

### ISSUE THREAD

**Issue by WillMorrison** [guardianproject/ChatSecureAndroid#602]
I had two chats open with two different people, on two different accounts. I selected the end chat menu item on one, and the name from the closed chat was shown on top instead of the name of the person in the remaining chat. This fixed itself when I navigated away from the chat screen and back.

Android chatsecure v14.0.9

**Comment by n8fr8** [comment]
this was fixed in v14.1.1 by moving back to the conversation list when you close the chat
