### ISSUE TITLE
ChatSecure forgets the MUC rooms

### ISSUE THREAD

**Issue by moshpirit** [guardianproject/ChatSecureAndroid#618]
That's the most important reason why I usually use Conversations instead of ChatSecure: if I join to a MUC room/group and I close CS, it forgets this room, so, please, at least, ad an option to forget them and autojoin us to them.
Please, excuse my English.

**Comment by wngr** [comment]
I'd like to see this feature, too. For me, its a dealbreaker at the moment.

**Comment by DjSlash** [comment]
This issue is a duplicate of (a part of) #515.

**Comment by moshpirit** [comment]
This issue it's more focused in that, but if the admin consider this a duplicate of 515, then, he can close this one, there's no problem at all, but I beg the team to please, implement this.

@DjSlash thanks for your comment and @wngr I think it's basic too, I hope they include this soon.

**Comment by moshpirit** [comment]
Ok, our petition has been listened :)  
Thank you, ChatSecure™
