### ISSUE TITLE
Bonjour missing since version 14.0.9?

### ISSUE THREAD

**Issue by ka223** [guardianproject/ChatSecureAndroid#622]
Hi,

I can not find Bonjour in this Version.
At 13.1.2 it is still available by "add existing account".

**Comment by TameOfGroans** [comment]
I am using 14.10.1 beta2

Add account 

http://i.imgur.com/rpbP4VX.jpg


Swipe right 

Swipe right (WiFi mesh) 

http://i.imgur.com/FetG9bA.jpg

Enter account name (Xmpp Texting) 

http://i.imgur.com/ksdaLJu.jpg

Sign in 

Ftw

Hth

**Comment by n8fr8** [comment]
Wifi Mesh = Bonjour

**Comment by TameOfGroans** [comment]
^ 14.1.0 b2

**Comment by ka223** [comment]
ok thanks, I found the Option at version 14.1.1-RC-2
