### ISSUE TITLE
cannot send photos or files

### ISSUE THREAD

**Issue by hodor22** [guardianproject/ChatSecureAndroid#628]
Hello Team,
I have a problem on my moto g . I cannot send fotos or files. It starts the send bar but stopps its after 1/4 . files are the same. the foto is shown inthe the chat but my chatpartner cannot see it. THe other way round for my chatpartner its the same with his fotos.

android 4.4.4

**Comment by 466** [comment]
Hi,
i guess one of my issues didn't make it into github last week;
I've got a similar problem. I'm on Android 4.1.2, using playstore version: 14.1.0-RC1a
I'm able to send files if those are relativly smal. A foto with 8MP, about 1.5MB takes about 45min. Small files <100KB do get transfered most of the time, but even that takes quite a long time.

**Comment by hodor22** [comment]
this is my problem 2

**Comment by 466** [comment]
Update:
I'm on 14.1.1, playstore.
Sending files does work, but it still needs far to much time ..... .
About 10s until a picute is sent from my cam to my CS 'chat-stream'
An other 40s until the picutre arrives at my tablet, file size: 52KB .... .

**Comment by n8fr8** [comment]
We've add image compression before transfer, which helps a great deal now. This will be provided in the next release. You can still send the full image by choosing the file/paperclip icon and sending it as a "file"/
