### ISSUE TITLE
axolotl support?

### ISSUE THREAD

**Issue by geohuhn23** [guardianproject/ChatSecureAndroid#650]
Hi guys, I am a big fan of xmpp, but at the moment it doesn't suit my needs (mobile messaging) I wanted to know how far you've come with the axolotl implementation yet

Thanks for any answers

**Comment by n8fr8** [comment]
What about XMPP doesn't support your needs? What is it about axolotl that you think it magically solves?

**Comment by geohuhn23** [comment]
It's strong encrypted asynchronous messaging, because both partners have to be online at the same time, to start a session. 

Pgp solves that, but hasn't the other features of otr (forward secrecy...)  and I think axolotl solves that problem quite good (with the prekeys) and it also supports end to end encrypted group chats. 

Thanks for the answer

**Comment by n8fr8** [comment]
With ChatSecure, we have long lived OTR sessions, and in fact, often renegotiate/ratchet sessions in the background when you are using the app. This means, unless you have a wildly different online/offline pattern than the people you communicate with, it is pretty rare you won't have an existing OTR session open with someone. Also, if the person is offline, you can send an encrypted message, and when they come online, the OTR session will be automatically renegotiated and the message resent without you needing to do anything. In summary, our implementation of XMPP+OTR works quite well in mobile contexts, while still maintaining compatibility with the many XMPP and OTR enabled clients and servers out there.

As far as I know, Axolotl doesn't support group messaging inherently (https://github.com/WhisperSystems/TextSecure/wiki/ProtocolV2), but it is achieved in TextSecure/Signal by using parallel sessions with each person in a group chat. Again, this is something we can do with XMPP+OTR and are planning to in our next release.

All in all, Axolotl is a good thing, but you shouldn't confuse that protocol with what the app/service is doing in its implementation.

**Comment by geohuhn23** [comment]
Okay thank you very much for your explanation. 

I used Chatsecure some time ago, and had quite big problems with message delivery and some messages couldn't be decrypted (I guess because the session was killed in the meantime) 

I will test it again in some time , thanks for your time

**Comment by devrandom** [comment]
Reliable message delivery is a problem, especially if the server and the other client don't support the relevant XMPP extensions (XEP-198 and XEP-184).

Do you remember what software was on the server and other client?

**Comment by geohuhn23** [comment]
I was using an older version of chatsecure on android, I used several severs (dukgo and two german severs) 

After that I changed to Telegram (I know it's not very good, but easy to use for people who don't care about encryption) threema and textsecure, but in the end i would like to host my own xmpp server with strong encryption for my family, but for that I need very reliable message delivery 

Thanks for your help 

That's why I'm asking

**Comment by devrandom** [comment]
Prosody support XEP-0198, which will make delivery a lot more reliable.  You just have to enable the `smacks` module.

Do you intend to use just ChatSecure, or also a desktop XMPP app on the same user ID?

**Comment by geohuhn23** [comment]
Thanks for the advise 

Yes all of the users will use multiple devices on the same user ID. 

There's a xep called carbon copy isn't it? For message synchronization on multiple devices. 

Can there be one long lived otr session with more than one device with the same user ID? 

Thanks for your help

**Comment by devrandom** [comment]
The problem is that each device has its own OTR state, so XMPP carbon copies are not useful.  Carbon copies for OTR would really be nice.

**Comment by geohuhn23** [comment]
Thank you for your explanation
