### ISSUE TITLE
Facebook IDs displayed as contact names

### ISSUE THREAD

**Issue by Jens14L** [guardianproject/ChatSecureAndroid#658]
ChatSecure 14.1.1-RC5 displays a block of Facebook IDs instead of the contact names after the online contacts and before the offline Jabber and Facebook contacts (with real contact names).

**Comment by hobarrera** [comment]
Note: Facebook XMPP support is closing in very few months, so I'd close this as WONTFIX, since it'll be useless work in the long run.

**Comment by hobarrera** [comment]
Oops, no it's not a few months, it's in a few hours (I came across this simply by coincidence just now).
