### ISSUE TITLE
Adding "Google Account" fails

### ISSUE THREAD

**Issue by bnvk** [guardianproject/ChatSecureAndroid#668]
Following these steps I read a dead end

1. Click on `+ Existing Account`
2. Click on `Account Type: Google Account`

I am left with a blank modal window that says "Account Type"

I'm running version 13.1.2 downloaded from F-Droid on CyanogenMod 12

**Comment by n8fr8** [comment]
You should try the latest ChatSecure here: https://guardianproject.info/releases/ChatSecure-v14.1.1-RC-5.apk or through our FDroid repo here: https://guardianproject.info/fdroid/repo/

For some reason, the ChatSecure build on F-Droid.org is very out of date. You will have to uninstall that version first.
