### ISSUE TITLE
cannot connect to jabberd2 due to missing 

### ISSUE THREAD

**Issue by gdt** [guardianproject/ChatSecureAndroid#677]
With 14.1.1RC5 on Android 4.4, I cannot log in to xmpp on jabberd 2.3.3.  The problem as discussed on guardian-dev is that the server does not send the session-supported capability, and ChatSecure (really in Smack) errors out.  However, the current protocol spec does not require sending session-supported:

https://tools.ietf.org/html/rfc6121#appendix-E

To fix, update Smack, as this has been fixed:

https://igniterealtime.org/issues/browse/SMACK-379

Smack also copes with problems due to this being optional:

https://igniterealtime.org/issues/browse/SMACK-622

**Comment by richardhansen** [comment]
Link to discussion thread:  http://thread.gmane.org/gmane.comp.encryption.guardian.devel/859
