### ISSUE TITLE
Receiving formatting appears to be wrong

### ISSUE THREAD

**Issue by BitPuffin** [guardianproject/ChatSecureAndroid#688]
Hello, first off I wanna thank you for creating ChatSecure, it's very useful! :+1: 

I'm mainly using ChatSecure as a client to Google Talk on my phone. And mostly it works ok. However, while sent messages look fine in ChatSecure, when I look at how they look in the browser they are very excessively spaces out, as illustrated in this picture: http://i.imgur.com/nhunBGr.png

I didn't put what looks like about 3-4 newlines between each message.

It's not a super major issue, but I think it could be annoying for those who is talking to people who are using ChatSecure.

I believe I'm using version 14.1.1

**Comment by n8fr8** [comment]
If you change the Chat Encryption setting to "As Requested" instead of "Automatically Attempt" it will stop injecting these blank lines. Also, that spacing should never show up for other people using ChatSecure, only for people who are not using an OTR capable client.
