### ISSUE TITLE
14.2.0 does multiple resending of messages even if they arrived

### ISSUE THREAD

**Issue by sniperle** [guardianproject/ChatSecureAndroid#699]
For me and my friends it's really annoying that 14.2.0 is re- and resending the last message to the receiver even if it already arrived. AFAIS happens this always after reconnecting. So if if you have an unstable connection this is really a no go and we had to downgrade to 14.1.1-rc5 until this problem is solved.

But thank you for the good work on ChatSecure keep going on.  :-)

**Comment by n8fr8** [comment]
When you say re and re-sending, how many times are you seeing these messages? Is it only when one side drops off and reconnects? Is this with OTR on or off? Are both sides using ChatSecure or just one?

We didn't see this happen in any of our testing, but we did make adjustments to our code in the area of on/offline sending, so I can imagine there is some set of circumstances where it is happening.

**Comment by sniperle** [comment]
Our configuration is OTR on. After the sender was offline and then goes online the last message is displayed on the receiver side again, this happens "endless". The sender does not see anything of this, just only the (one) original message. Both sides with ChatSecure.

**Comment by srguglielmo** [comment]
I have experienced this as well. I notice it begins happening during a "sketchy" data connection - like going underground in a subway. It continues to happen when logging back online. I get the same message anywhere from 2-4 times every time I log out and then back in again. Both sides chatsecure-android. It started happening with the latest release, 14.2.0.

**Comment by srguglielmo** [comment]
More info: The message that is repeating seems to be the first message in a conversation (like when you start and end a convo by going to "End chat"). Even if that conversation is ended (via the "End Chat" option), the account deleted on one end, then added again, it still repeats that first initial message AND the new initial message. At this point, I'm getting repeats of 4 initial messages from different convos with the same user. All 4 messages are reset/delivered over and over when the other end disconnects/connects.

I received these repeat messages when the OTHER user switched from cellular data to a wifi connection. Again, it seems to happen on changes to the data connection.

**Comment by n8fr8** [comment]
Thanks for all the detail. It seems the re-send/offline/queue logic we added is overzealous and overcompensating.

**Comment by n8fr8** [comment]
Sorry this has taken so long to fix, but it has been fixed now in this pull request: https://github.com/guardianproject/ChatSecureAndroid/pull/706 

We'll finish testing and ship an update this week.

**Comment by n8fr8** [comment]
There is a release candidate build posted here: https://guardianproject.info/releases/ChatSecure-v14.2.1.apk

**Comment by srguglielmo** [comment]
Can confirm this was fixed in 14.2.1!

**Comment by austin987** [comment]
Works for me in 14.2.1 as well, please consider pushing this release to the play store.

**Comment by n8fr8** [comment]
Oh I thought we did! Grrr. Will make that happen.

**Comment by K1773R** [comment]
Has this been pushed to the play store?
Its very annoying...

**Comment by Max42** [comment]
Hey Guys what do you make all the day? When comes the update of chat secure in the playstore?

**Comment by n8fr8** [comment]
14.2.1  was published to Google Play.
