### ISSUE TITLE
Modifying sqlite database

### ISSUE THREAD

**Issue by sakalauskas** [guardianproject/ChatSecureAndroid#703]
Hello,

I need to install this application on multiple devices, therefore I would need install the apk file and then push the sqlite database to the device.

The issue that each phone need to have different account and therefore I need to modify the database, but it is encrypted with SQLCipher.

How can I do this effectively? Or can I remove the SQLCipher somehow easily?

Thanks a lot for the help.

**Comment by n8fr8** [comment]
Why do you need to push a sqlite database? You are trying to auto-install to many devices, so you want to configure some sort of default settings? You would also need to have root on the device to be able to do that.

There are sqlcipher command line tools available at https://sqlcipher.net I believe, so that you can work with SQLCipher databases on the desktop/server.

**Comment by sakalauskas** [comment]
Yes, that is correct, phones are preinstalled with custom ROMS, and I am aware of that, so root is not an issue. 

Sorry, haven't looked much on the source code, yet. But as far as I understand the database is encrypted with a key that it is set on first launch of the app? So if the key is not set - database is not encrypted and can be easily edited?

**Comment by n8fr8** [comment]
If you don't use the app lock password feature (the key is null/not set), then the password to the database is just an empty string.

https://github.com/guardianproject/ChatSecureAndroid/blob/master/src/info/guardianproject/otr/app/im/app/WelcomeActivity.java#L566

You could run ChatSecure, skip the app password feature, setup one account in the app, then copy that database file to your deployment setup as the template. Then using SQLCipher command line tools, you can modify the values in the schema, to customize for each user.

You can find all the schema information here:
https://github.com/guardianproject/ChatSecureAndroid/blob/master/src/info/guardianproject/otr/app/im/provider/ImpsProvider.java

You will want to change data in the accounts table:
https://github.com/guardianproject/ChatSecureAndroid/blob/master/src/info/guardianproject/otr/app/im/provider/ImpsProvider.java#L322

**Comment by sakalauskas** [comment]
Thanks very much Nathan, you are a hero!

**Comment by n8fr8** [comment]
No problem. Happy you are using our app in this way. Would love to hear more about your project/product/service if you want to or can share.
