### ISSUE TITLE
how do i create a chat group? 

### ISSUE THREAD

**Issue by chasquicamilo** [guardianproject/ChatSecureAndroid#714]
i´m a new user of chat secure, i don´t know much of encrypted comunications but we really needed. I have already get encripted talking ono to one, but i don´t know what server to use un the group chat, just because the app don´t give me any options. somebody can help me?

**Comment by dcharles525** [comment]
I don't believe that feature is included in this app.

**Comment by chasquicamilo** [comment]
Yes, it has. Group Chat, but just doesn´t seem to work. Anyway we 
already take actions, we are not going to use Chat Secure, instead we 
are using TextSecure because is better. thanks anyway :)

**Comment by chseluv** [comment]
you have to use the conference server that your XMPP service provides if there is any, otherwise you need to make sure you're using a service that does in order to be able to use chat groups. It's generally called "conference.x.y" like in "conference.dukgo.com"

**Comment by n8fr8** [comment]
You can also use conference.rows.io which is an open conference server.

You can also try Conversations.im group chat feature, which works a bit better than ChatSecure's does currently.
