### ISSUE TITLE
Getting java.lang.ClassNotFoundException: "info.guardianproject.otr.app.im.app.WelcomeActivity"

### ISSUE THREAD

**Issue by shubh06** [guardianproject/ChatSecureAndroid#717]
I have imported all the projects as described on Github.When i tried to run the application its gets crashed with runtime exception.

 java.lang.ClassNotFoundException: Didn't find class "info.guardianproject.otr.app.im.app.WelcomeActivity" on path: DexPathList[[zip file "/data/app/info.guardianproject.otr.app.im-2/base.apk"],nativeLibraryDirectories=[/data/app/info.guardianproject.otr.app.im-2/lib/arm, /vendor/lib, /system/lib]]

**Comment by n8fr8** [comment]
This codebase is coming to the end of its life. There are two other projects to work on now.

Zom is based on this project but updated for Android Studio and Gradle: https://github.com/zom/Zom-Android

Conversations is another XMPP application with encryption support: https://github.com/siacs/Conversations/

**Comment by n8fr8** [comment]
For more information, please read here: https://chatsecure.org/blog/chatsecure-conversations-zom/

**Comment by shubh06** [comment]
Thank you  for the reply, information that you have provide to us was really helpful.
