### ISSUE TITLE
Sending pictures from ChatSecure to Pidgin client over XMPP (OTR encrypyted chat): message is lost

### ISSUE THREAD

**Issue by austin987** [guardianproject/ChatSecureAndroid#720]
Sending text in either direction works fine, but if I attempt to send a picture in an encrypted chat to a pidgin user (Pidgin 2.10.11 (libpurple 2.10.11), OTR version 4.0.1), the message is lost (appears sent to the ChatSecure client).

Chat secure is version 14.2.1

**Comment by n8fr8** [comment]
Pidgin doesn't support encrypted file transfer.

**Comment by austin987** [comment]
Ah, do you know if there's an upstream bug for that?

Does CS know that pidgin doesn't support encrypted file transfert, so it can block/warn the user that the message will be lost?

**Comment by n8fr8** [comment]
Not sure about Pidgin. I think there is a lot of flux right now around encrypted file transfers, since there are many ways to do it, and no one quite agrees yet.

CS shouldn't show that it was transfered, so that is definitely a bug.

**Comment by chseluv** [comment]
Another thing happens that I think should be considered.

There are jabber servers that require OTR communications and pictures transfers will result in an error at the current state of ChatSecure (note: the Android version is the only one I tried).

Between regular XMPP servers users, even during an OTR session, pics can be sent back and forth. I wrongly supposed that the same would happen between OTR-forcing servers but it's not the case and the aforementioned servers send error messages stating that OTR encryption is mandatory. Am I right in assuming pics are converted to base64 and then sent like text messages? If that is so, couldn't they be also OTR-encrypted and that is what is not happening which causes these errors?

As you can read here https://ssd.eff.org/en/module/how-install-and-use-chatsecure they seem to suggest that pictures are encrypted during transfers in ChatSecure when the OTR fingerprint is verified, which I'm not sure to have tested.. do you agree?

**Comment by n8fr8** [comment]
We use our OTRDATA system for all media sharing, which means all shared files are encrypted in the same session as your chat messages. We do essentially send them as Base64 chunks inside of OTR. They are fully encrypted end-to-end just like chat, and they do work on OTR forcing services just fine.
