### ISSUE TITLE
>src in the project error

### ISSUE THREAD

**Issue by rizkyherliana** [guardianproject/ChatSecureAndroid#727]
I have been importing the project to eclipse and I did. But there are many errors in >src such as 
inside info.guardianproject.onionkit.ui , com.google.zxing.intergration.android and many else below of it

**Comment by n8fr8** [comment]
Please view the readme and build instructions for how to retrive all of the git submodules properly.

Also, you can take a look at our next-gen chat client called Zom, which is now here: https://github.com/zom/zom-android and uses Android Studio and Gradle.
