### ISSUE TITLE
XMPPConnection.connect won't return when running in Android 6.0 (Marshmallow)

### ISSUE THREAD

**Issue by clementcho** [guardianproject/ChatSecureAndroid#728]
Dear Admin,
I have been working on ChatSecure and I have convert part of the code to compile in Android 6 SDK. The Code is compiled but the software is stuck in login procedure. The software didn't freeze or hang. The Account just stay in "Signing in". 
I trace down to the (MyXMPPConnection) mConnection.connect() (XmppConnection.java line 1486) method won't return. I am suspecting the asmack-android8 is not compatible with Android 6.0. and I have been trying to upgrade it to Smack 4.1.5 or asmack-android-16. They both come back with compile error that missing library, such as 
org.jivesoftware.smack.PacketListener;
org.jivesoftware.smack.Roster;...
are ones of many that is not present in the new library.  

I am wondering if you guys already have a solution for this problem or working on it.
My test device is Nexus 6 in Android 6.0. The Chatsecure in Playstore has the same problem of logging in.

Thanks,
Clement

**Comment by chseluv** [comment]
I confirm the issue. I'm going to gather details from users and if I learn something useful I will provide it

**Comment by adahary** [comment]
Should the current ChatSecure-latest.apk from direct download link has this fix and therefore will be able to  login on an Android.6.M device?
