### ISSUE TITLE
Unable to send file between Chatsecure and pidgin xmpp

### ISSUE THREAD

**Issue by rabbit111** [guardianproject/ChatSecureAndroid#740]
Hello,
Thank you for great job in developing chatsecure! 
I can write to others between CS and pidgin via OTR. It works great!
but
I cannot send files from pidgin to chatsecure and from chatsecure to pidgin.
Sending files from chatsecure to chatsecure works perfect.
Regards

**Comment by Jens14L** [comment]
Conversations uses a current protocol, libpurple (Pidgin) and ChatSecure other, older protocols, I think.
See https://developer.pidgin.im/ticket/16555

**Comment by vindicatorr** [comment]
Should I assume that is also the case with jitsi? I can't transfer to/from jitsi and conversations/chatsecure.
From jitsi:
```
 The above message could not be delivered
Failed to deliver message.
```
To jitsi:
```
?FILETRANSFERv1:<hash/key value?>
```
What PC xmpp program (with otr,(jingle)... like jitsi) does support new protocols?

**Comment by n8fr8** [comment]
None of them unfortunately. The only encrypted file transfer that exists is supported by ChatSecure and Conversations using currently incompatible standards. We are working both to converge on the same standard, and to push other XMPP apps to adopt something as well.

We have toyed with the idea of adding support for unencrypted file transfer in order to have compatibility with desktop apps, but that wouldn't really be living up to our name unfortunately.

**Comment by austin987** [comment]
@n8fr8 is there another issue I can follow that tracks the convergence?

**Comment by n8fr8** [comment]
https://github.com/ChatSecure/ChatSecure-iOS/issues/376

**Comment by vindicatorr** [comment]
Ah yes, I'm seeing the OMEMO stuff https://chatsecure.org/blog/chatsecure-conversations-zom/
Gajim (PC/Desktop) has a plugin for it, but I'm not liking it. I can't find my fingerprint in Gajim (I can in Conversations) and I can't send OMEMO messages from Gajim (red 'X' after my message). There's also a red shield to the left of the text box which needs authentication I think.

**Comment by austin987** [comment]
Thanks @n8fr8. I realize you probably don't want to maintain two codepaths for Android and iPhone, but IMO if the library is likely to be relicensed anyway, the code could be written now (potentially in a branch), and only enabled for Android. Once it is relicensed, enable it on IOS. That would allow earlier testing (and better functionality) for Android users, without compromising your legal position with Apple.

In any case, thanks for the link and your work, I'll watch that issue.
