### ISSUE TITLE
ChastSecure - Double Tick?

### ISSUE THREAD

**Issue by lowlife10** [guardianproject/ChatSecureAndroid#741]
When chatting in ChatSecure, what does the double tick mean in stead of 1 tick?

Also, what does it mean when there's a 'x' and a tick beside each other instead of 2 ticks?

**Comment by n8fr8** [comment]
one tick means sen out from your device to the server, two ticks means it has been delivered/received by the other side.

X means it has not been sent, or possibly not received.
