### ISSUE TITLE
Do we have gradle Android studio version for chat secure? 

### ISSUE THREAD

**Issue by gurpreetlucky** [guardianproject/ChatSecureAndroid#744]
The Code is still exists in eclipse . Does it converted to Android studio ? any link ?

**Comment by ruha9005** [comment]
It still not converted to android Studio. Dear devs, please, conert it to it:)

**Comment by n8fr8** [comment]
This is the Gradle version of ChatSecure. It is now called Zom: https://github.com/zom/Zom-Android
and has many, many other improvements.

**Comment by n8fr8** [comment]
You might also want to check out Conversations, if you want a more plain vanilla XMPP app project: https://conversations.im/
