### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by AlphaOmega3** [guardianproject/ChatSecureAndroid#758]
Hi! Is possible load the new version of ChatSecure on F-Droid (in Guardian Project Official Releases repo)??

**Comment by n8fr8** [comment]
We aren't developing ChatSecure directly anymore. Instead, you should use Conversations (available on F-Droid) or try Zom.im (available on Play or direct APK at http://zom.im).

The last release was simply a message prompt telling users they should switch to one of these two apps.

ChatSecure iOS is still under active development, and partering with Conversations closely on Android to add next-generation encryption support.
