### ISSUE TITLE
Kill this Repo

### ISSUE THREAD

**Issue by Miserlou** [guardianproject/ChatSecureAndroid#762]
Since the project has been hard-forked to Zom (here: https://github.com/zom/Zom-Android), but people are still filing issues here, I suggest that you kill the contents of this repo except for a README file to redirect to the new project. 

This is causing a lot of confusion online, such as here: https://news.ycombinator.com/item?id=13425363

**Comment by Atavic** [comment]
This repository should be *read only*.

**Comment by abeluck** [comment]
@n8fr8  ping

I've submitted a PR for the README, but the repo settings need to be changed and the URL/description of the repo should be changed too probably (it currently points to the defunct dev.gp.i).

Thanks for bringing this up @Miserlou ad @Atavic
