### ISSUE TITLE
GB should use more subtle OTR Query Messages

### ISSUE THREAD

**Issue by Hooloovoo** [guardianproject/ChatSecureAndroid#96]
So far, every single person that I have talked to through Gibberbot has asked why I am sending them messages saying "?OTRv2?". Most take the inference that I have something to hide. It does not seem possible to turn these messages off.

According to the protocol:
http://www.cypherpunks.ca/otr/Protocol-v2-3.0.0.html
"These strings may be hidden from the user (for example, in an attribute of an HTML tag)."

If for some reason it can't be hidden in this way, it appears that "Tagged plaintext messages" (whitespace) can be used to subtly indicate that the client supports OTR.

It would be great if the messages were more subtle, so that nobody would notice that I supported OTR unless they are also using an OTR client.

**Comment by n8fr8** [comment]
We do use tagged whitespace messages most of the time. We only send the ?OTRv2? query messages if you are actively trying to start and encrypted chat.
